<template>
    <div class="loading">
        <div class="loadingio-spinner-spinner-loakknhsc9">
            <div class="ldio-ve6lgacnzm">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>
</template>
<style type="text/css">
    @keyframes ldio-ve6lgacnzm {
        0% {
            opacity: 1
        }
        100% {
            opacity: 0
        }
    }
    .loading {background: white;opacity: 7;position: fixed;top: 0;left: 0;z-index: 999;width: 100%;height: 100%;display: none}
    .loading.show {display: block}
    .loadingio-spinner-spinner-loakknhsc9 {position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%,-50%);
    }
    .ldio-ve6lgacnzm div {
        left: 50%;
        top: 48px;
        position: absolute;
        animation: ldio-ve6lgacnzm linear 1s infinite;
        background: #fe718d;
        width: 12px;
        height: 24px;
        border-radius: 6px / 12px;
        transform-origin: 6px 52px;
    }

    .ldio-ve6lgacnzm div:nth-child(1) {
        transform: rotate(0deg);
        animation-delay: -0.9166666666666666s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(2) {
        transform: rotate(30deg);
        animation-delay: -0.8333333333333334s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(3) {
        transform: rotate(60deg);
        animation-delay: -0.75s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(4) {
        transform: rotate(90deg);
        animation-delay: -0.6666666666666666s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(5) {
        transform: rotate(120deg);
        animation-delay: -0.5833333333333334s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(6) {
        transform: rotate(150deg);
        animation-delay: -0.5s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(7) {
        transform: rotate(180deg);
        animation-delay: -0.4166666666666667s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(8) {
        transform: rotate(210deg);
        animation-delay: -0.3333333333333333s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(9) {
        transform: rotate(240deg);
        animation-delay: -0.25s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(10) {
        transform: rotate(270deg);
        animation-delay: -0.16666666666666666s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(11) {
        transform: rotate(300deg);
        animation-delay: -0.08333333333333333s;
        background: #fe718d;
    }

    .ldio-ve6lgacnzm div:nth-child(12) {
        transform: rotate(330deg);
        animation-delay: 0s;
        background: #fe718d;
    }

    .loadingio-spinner-spinner-loakknhsc9 {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: #ffffff;
    }

    .ldio-ve6lgacnzm {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }

    .ldio-ve6lgacnzm div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>
<script>
    export default {
        name: 'loading',
        data() {
            return {}
        }
    }
</script>